### ISSUE TITLE
Rule evaluates wrong

### ISSUE THREAD

**Issue by jrhaddad** [advantagefse/json-logic-swift#24]
Hi,

Json-logic-swift is very useful for our development. It works great overall. Thank you!

We discovered a case where a rule does't evaluate to the same result compared to the test tool on https://jsonlogic.com/play.html . Assuming jsonlogic.com is the reference implementation, we think there might be a bug in json-logic-swift.

Here is the test case. It evaluates to TRUE on jsonlogic.com and FALSE with json-logic-swift.

Rule:
{"!": [
  {"and" : [
    {"in":["Population", { "var" : "CHOIX" }]},
    {"in" : [ { "var" : "TAILLE_POP" }, ["", null] ]}
  ]}
]}

Data:
{ "COMPARTIEMENT" : "Faune/Wildlife", "ACTIF" : "false" }

Have a great day,

Jean-Robert

**Comment by csknns** [comment]
Thanks for reporting this @jrhaddad . This is indeed a bug, I will provide a fix for this soon!

**Comment by csknns** [comment]
fixed in #25 !
