### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by d-srd** [advantagefse/json-logic-swift#3]
The last sentence of the README states that this project is licensed under LGPL. However, the project's LICENSE file has the regular GNU GPLv3 license. What's the actual license?

**Comment by csknns** [comment]
Hello @d-srd. The License of the project is LGPL(i.e. GNU LESSER GENERAL PUBLIC LICENSE). If you open the LICENSE file you can see the first line that has the license name is "GNU LESSER GENERAL PUBLIC LICENSE", you can also check the license text from  https://www.gnu.org/licenses/lgpl-3.0.txt. Github recognizes it as 'GNU Lesser General Public License v3.0'

**Comment by d-srd** [comment]
Looks like I've misread the LICENSE file – my mistake.
