### ISSUE TITLE
Any plans to support add_operation?

### ISSUE THREAD

**Issue by chamitha** [advantagefse/json-logic-swift#7]
The add_operation allows extending JsonLogic using custom libraries inside the rules. Is there any plans to support this?
https://jsonlogic.com/add_operation.html

**Comment by csknns** [comment]
@chamitha Thanks for your input! I took a look of add operation and it looks easy to implement without exposing the parsing internals. Do you need this for your project?

I am thinking something like registering for each new operation a closure that takes an JSON(input data) and return a result JSON:
```
        ["plus": { (json: JSON) in
            return json.array[0].int + json.array[1].int
        }]
```
 
And then we could parse a rule like `{ "plus" : [1, 2] }` 

I will include this in the next release

**Comment by csknns** [comment]
@chamitha  I have included the add operation in the master, you check the Readme for how to use it!

It will be included in the next release

**Comment by chamitha** [comment]
Thanks @csknns. I think this should serve the purpose. I'll give it a test in a couple of weeks when I get back to my task at hand that required this operation.

**Comment by csknns** [comment]
Thanks @chamitha, any feedback to improve the library is welcome.

**Comment by chamitha** [comment]
@csknns I'm trying to test this using the master branch but coming across the following compile error in the Parser.swift file.
Value of type 'JSON' has no member 'truthy'

**Comment by csknns** [comment]
@chamitha I published a new version 1.1.0, that includes the correct version of the json-enum dependency(that the jsonlogiv depndends on and I renamed the truthy). Can you try with the 1.10?

**Comment by chamitha** [comment]
Thanks @csknns, upgrading resolves the issue.

**Comment by chamitha** [comment]
@csknns 
I have tested the custom operations and it works brilliantly as expected. Many thanks for this update!
My only suggestion is to include an `addOperation` method to instead (or in addition) to the constructor as this is more consistent with the JsonLogic spec and your Kotlin library.

**Comment by csknns** [comment]
I am glad it works & it is useful! Thanks for making suggestion to improve this library!

I will probably add an `addOperation` method in the next release to have the same interface as the Kotlin library
